# Generated by Django 5.2.11 on 2026-02-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name_plural': 'SubCounties'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'verbose_name_plural': 'Wards'},
        ),
    ]
