# Generated by Django 5.2.11 on 2026-02-09 20:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0002_alter_county_options_alter_subcounty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bore_hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('yield_m3hr', models.FloatField(blank=True, null=True)),
                ('well_depth_m', models.FloatField(blank=True, null=True)),
                ('operational_status', models.CharField(blank=True, max_length=100, null=True)),
                ('drilling_method', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('first_stratum', models.CharField(blank=True, max_length=255, null=True)),
                ('second_stratum', models.CharField(blank=True, max_length=255, null=True)),
                ('third_stratum', models.CharField(blank=True, max_length=255, null=True)),
                ('water_restriction', models.CharField(blank=True, max_length=255, null=True)),
                ('electrical_conductivity', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waterpoints.ward')),
            ],
        ),
    ]
