# Generated by Django 5.2.11 on 2026-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0003_bore_hole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bore_hole',
            options={'verbose_name_plural': 'Boreholes'},
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='drilling_method',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='electrical_conductivity',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='elevation_m',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='first_stratum',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='operational_status',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='second_stratum',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='source',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='temperature_c',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='third_stratum',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='water_restriction',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='well_depth_m',
        ),
        migrations.RemoveField(
            model_name='bore_hole',
            name='yield_m3hr',
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='admin_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='drilling_e',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='ec',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='elevation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='first_stru',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='operation_field',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='second_str',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='source_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='temperatur',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='third_stru',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='water_rest',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='well_depth',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='yield_value',
            field=models.FloatField(blank=True, db_column='yield', null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='locality',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
