# Generated by Django 5.2.11 on 2026-02-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0004_alter_bore_hole_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bore_hole',
            table='bore_hole',
        ),
    ]
