# Generated by Django 5.2.11 on 2026-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0005_alter_bore_hole_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bore_hole',
            name='operation_field',
            field=models.CharField(blank=True, db_column='operation_', max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='bore_hole',
            table=None,
        ),
    ]
