# Generated by Django 5.2.11 on 2026-02-13 07:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0006_alter_bore_hole_operation_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_deg', models.FloatField(blank=True, null=True)),
                ('lon_deg', models.FloatField(blank=True, null=True)),
                ('status_id', models.CharField(blank=True, max_length=254, null=True)),
                ('report_dat', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('water_sour', models.CharField(blank=True, max_length=254, null=True)),
                ('water_tech', models.CharField(blank=True, max_length=254, null=True)),
                ('clean_coun', models.CharField(blank=True, max_length=254, null=True)),
                ('clean_co_1', models.CharField(blank=True, max_length=254, null=True)),
                ('clean_adm1', models.CharField(blank=True, max_length=254, null=True)),
                ('clean_adm2', models.CharField(blank=True, max_length=254, null=True)),
                ('clean_adm3', models.CharField(blank=True, max_length=254, null=True)),
                ('install_ye', models.BigIntegerField(blank=True, null=True)),
                ('installer', models.CharField(blank=True, max_length=254, null=True)),
                ('management', models.CharField(blank=True, max_length=254, null=True)),
                ('pay_clean', models.CharField(blank=True, max_length=254, null=True)),
                ('status_cle', models.CharField(blank=True, max_length=254, null=True)),
                ('subjective', models.CharField(blank=True, max_length=254, null=True)),
                ('local_popu', models.BigIntegerField(blank=True, null=True)),
                ('assigned_p', models.BigIntegerField(blank=True, null=True)),
                ('facility_t', models.CharField(blank=True, max_length=254, null=True)),
                ('water_so_1', models.CharField(blank=True, max_length=254, null=True)),
                ('water_te_1', models.CharField(blank=True, max_length=254, null=True)),
                ('created_ti', models.CharField(blank=True, max_length=254, null=True)),
                ('dataset_ti', models.CharField(blank=True, max_length=254, null=True)),
                ('rehab_prio', models.BigIntegerField(blank=True, null=True)),
                ('would_gain', models.BigIntegerField(blank=True, null=True)),
                ('usage_cap', models.BigIntegerField(blank=True, null=True)),
                ('criticalit', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('distance_t', models.FloatField(blank=True, null=True)),
                ('distance_1', models.FloatField(blank=True, null=True)),
                ('distance_2', models.FloatField(blank=True, null=True)),
                ('distance_3', models.FloatField(blank=True, null=True)),
                ('distance_4', models.FloatField(blank=True, null=True)),
                ('is_urban', models.CharField(blank=True, max_length=254, null=True)),
                ('days_since', models.BigIntegerField(blank=True, null=True)),
                ('staleness', models.FloatField(blank=True, null=True)),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('predicti_1', models.FloatField(blank=True, null=True)),
                ('predicti_2', models.FloatField(blank=True, null=True)),
                ('predicti_3', models.FloatField(blank=True, null=True)),
                ('predicted_field', models.CharField(blank=True, max_length=254, null=True)),
                ('predicted1', models.CharField(blank=True, max_length=254, null=True)),
                ('predicte_1', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Water Point',
                'verbose_name_plural': 'Water Points',
            },
        ),
    ]
