# Generated by Django 5.2.11 on 2026-02-24 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpoints', '0007_water_points'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='water_points',
            table_comment='Water points data with spatial and attribute information',
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bore_hole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='water_points',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water_points',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='water_points',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='admin_1',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='ec',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='locality',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='operation_field',
            field=models.CharField(blank=True, db_column='operation_', db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='ph',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='source_1',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bore_hole',
            name='yield_value',
            field=models.FloatField(blank=True, db_column='yield', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='subcounty',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='subcounty',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='assigned_p',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='clean_adm1',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='clean_adm2',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='clean_adm3',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='clean_co_1',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='clean_coun',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='install_ye',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='lat_deg',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='local_popu',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='lon_deg',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='management',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='report_dat',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='status_cle',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='status_id',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='water_sour',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='water_points',
            name='water_tech',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['operation_field'], name='waterpoints_operati_8c40a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['admin_1'], name='waterpoints_admin_1_255619_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['country'], name='waterpoints_country_3aac57_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['locality'], name='waterpoints_localit_bdfd66_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['yield_value'], name='waterpoints_yield_bcf6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['ec'], name='waterpoints_ec_7f2819_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['ph'], name='waterpoints_ph_f3afb5_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['admin_1', 'operation_field'], name='waterpoints_admin_1_276dca_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['admin_1', 'yield_value'], name='waterpoints_admin_1_69210f_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['latitude', 'longitude'], name='waterpoints_latitud_a92cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['-updated_at'], name='waterpoints_updated_278ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='bore_hole',
            index=models.Index(fields=['-created_at'], name='waterpoints_created_481915_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['county'], name='waterpoints_county_b13090_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['country'], name='waterpoints_country_af8ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['county'], name='waterpoints_county_9ed94e_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['subcounty'], name='waterpoints_subcoun_6f3029_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['country'], name='waterpoints_country_eb440b_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['province'], name='waterpoints_provinc_464dda_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['county'], name='waterpoints_county_82982a_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['subcounty'], name='waterpoints_subcoun_36125e_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward'], name='waterpoints_ward_deaee8_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['status_cle'], name='waterpoints_status__d4c699_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['report_dat'], name='waterpoints_report__7e3bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['status_id'], name='waterpoints_status__cbf23a_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm1'], name='waterpoints_clean_a_3104bc_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm2'], name='waterpoints_clean_a_c298be_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm3'], name='waterpoints_clean_a_08a5df_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_coun'], name='waterpoints_clean_c_ee7c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['water_sour'], name='waterpoints_water_s_2df778_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['water_tech'], name='waterpoints_water_t_c8146e_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['source'], name='waterpoints_source_8fd0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['management'], name='waterpoints_managem_46c638_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['assigned_p'], name='waterpoints_assigne_02eba2_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['local_popu'], name='waterpoints_local_p_5e9de1_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['install_ye'], name='waterpoints_install_dacd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm1', 'status_cle'], name='waterpoints_clean_a_82004f_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm1', 'water_sour'], name='waterpoints_clean_a_e2f555_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['clean_adm1', 'assigned_p'], name='waterpoints_clean_a_c0bce8_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['report_dat', 'status_cle'], name='waterpoints_report__f32815_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['lat_deg', 'lon_deg'], name='waterpoints_lat_deg_874bef_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['is_valid'], name='waterpoints_is_vali_b149a6_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['-updated_at'], name='waterpoints_updated_6bddd8_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['-created_at'], name='waterpoints_created_f48c16_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['staleness'], name='waterpoints_stalene_6bca2f_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['days_since'], name='waterpoints_days_si_b1e03e_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['rehab_prio'], name='waterpoints_rehab_p_48b224_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['criticalit'], name='waterpoints_critica_63e199_idx'),
        ),
        migrations.AddIndex(
            model_name='water_points',
            index=models.Index(fields=['pressure'], name='waterpoints_pressur_edc69f_idx'),
        ),
    ]
